# Generated by Django 4.0.1 on 2022-02-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_taken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='total_available_leave',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
