# Generated by Django 4.0.1 on 2022-03-09 05:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='enddate',
            field=models.DateField(default=django.utils.timezone.now, help_text='coming back on ...', verbose_name='End Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leavetype',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('emergency', 'Emergency Leave'), ('study', 'Study Leave'), ('annual', 'Annual Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('bereavement', 'Bereavement Leave'), ('quarantine', 'Self Quarantine'), ('compensatory', 'Compensatory Leave'), ('sabbatical', 'Sabbatical Leave')], default='sick', max_length=25),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='startdate',
            field=models.DateField(default=django.utils.timezone.now, help_text='leave start date is on ..', verbose_name='Start Date'),
            preserve_default=False,
        ),
    ]
