# Generated by Django 4.0.1 on 2022-02-07 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leaverequest_is_rejected_leaverequest_leave_taken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='status',
        ),
    ]
