# Generated by Django 4.0.1 on 2022-02-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_remove_leaverequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='leave_taken',
            new_name='leave_duration',
        ),
    ]
