# Generated by Django 4.0.1 on 2022-02-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state_code',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='tin_number',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
    ]
