# Generated by Django 4.0.1 on 2022-02-08 10:51

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_state_state_code_alter_state_tin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
