# Generated by Django 4.0.1 on 2022-02-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_shop_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='region',
        ),
        migrations.AddField(
            model_name='shop',
            name='contact_number2',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
