# Generated by Django 4.0.1 on 2022-03-03 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0002_alter_salesexecutivetarget_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesexecutive',
            old_name='employ_id',
            new_name='employe_id',
        ),
    ]
