# Generated by Django 4.0.1 on 2022-03-09 06:14

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenses",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
