# Generated by Django 4.0.3 on 2022-03-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryadavance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='salaryadavance',
            name='max_amount',
        ),
        migrations.AddField(
            model_name='salaryadavance',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
