# Generated by Django 4.0.1 on 2022-02-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinators', '0003_salesmanagertask_salescoordinatortask'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescoordinatortarget',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salescoordinatortask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesmanagertarget',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesmanagertask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
