# Generated by Django 4.0.1 on 2022-02-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinators', '0004_salescoordinatortarget_is_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salescoordinatortarget',
            old_name='amount',
            new_name='current_amount',
        ),
        migrations.RenameField(
            model_name='salesmanagertarget',
            old_name='amount',
            new_name='current_amount',
        ),
        migrations.AddField(
            model_name='salescoordinatortarget',
            name='target_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesmanagertarget',
            name='target_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
