# Generated by Django 4.0.1 on 2022-02-17 10:46

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('coordinators', '0005_rename_amount_salescoordinatortarget_current_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescoordinator',
            name='employ_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='salesmanager',
            name='employ_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesmanager',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
