# Generated by Django 4.0.1 on 2022-03-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinators', '0006_salescoordinator_employ_id_salesmanager_employ_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salescoordinatortarget',
            name='month',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=3),
        ),
        migrations.AlterField(
            model_name='salesmanagertarget',
            name='month',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=3),
        ),
    ]
