# Generated by Django 4.0.1 on 2022-03-03 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinators', '0007_alter_salescoordinatortarget_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salescoordinator',
            old_name='employ_id',
            new_name='employe_id',
        ),
        migrations.RenameField(
            model_name='salesmanager',
            old_name='employ_id',
            new_name='employe_id',
        ),
    ]
