# Generated by Django 4.0.1 on 2022-03-07 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="region",
            field=models.ForeignKey(
                limit_choices_to={"is_deleted": False},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.region",
            ),
        ),
    ]
