# Generated by Django 4.0.1 on 2022-02-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='designation',
        ),
        migrations.AddField(
            model_name='user',
            name='employ_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
