# Generated by Django 4.0.1 on 2022-02-14 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_designation_user_employ_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_sales_exicutive',
            new_name='is_sales_executive',
        ),
    ]
