# Generated by Django 4.0.1 on 2022-02-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_is_sales_exicutive_user_is_sales_executive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employ_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
