# Generated by Django 4.0.1 on 2022-03-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_employ_id_remove_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employ_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
