# Generated by Django 4.0.3 on 2022-03-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_darnotes_dar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dartask',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='darnotes',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
