# Generated by Django 4.0.3 on 2022-03-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_employeedocumentsitems_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocumentsitems',
            name='image',
            field=models.FileField(upload_to='documents_single'),
        ),
    ]
