# Generated by Django 4.0.3 on 2022-03-22 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_employeedocumentsitems_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocumentsitems',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.employeedocuments'),
        ),
    ]
