# Generated by Django 4.0.3 on 2022-03-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_employeedocumentsitems_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocumentsitems',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='document/'),
        ),
    ]
