# Generated by Django 4.0.1 on 2022-02-05 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandiser',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Mark as Deleted')),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone Number')),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True, verbose_name='User Adress')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('photo', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='accounts/user/photo/', verbose_name='User Profile Photo')),
                ('visa_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Visa Number')),
                ('visa_expiry', models.DateField(blank=True, null=True, verbose_name='Visa Expiry Date Number')),
                ('passport_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Passport Number')),
                ('passport_expiry', models.DateField(blank=True, null=True, verbose_name='Visa Expiry Date Number')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
                ('creator', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shop')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.state')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
