# Generated by Django 4.0.1 on 2022-02-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandiser', '0003_merchandisertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandisertarget',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchandisertask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
