# Generated by Django 4.0.1 on 2022-02-15 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandiser', '0005_rename_amount_merchandisertarget_current_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandiser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='merchandiser',
            name='region',
        ),
    ]
