# Generated by Django 4.0.1 on 2022-02-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandiser', '0006_remove_merchandiser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandiser',
            name='employ_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
