# Generated by Django 4.0.1 on 2022-03-03 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandiser', '0008_alter_merchandisertarget_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchandiser',
            old_name='employ_id',
            new_name='employe_id',
        ),
    ]
