# Generated by Django 4.0.3 on 2022-03-23 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_remove_loan_user_alter_loan_guarntee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='max_amount',
        ),
    ]
