# Generated by Django 4.0.3 on 2022-03-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_remove_loan_max_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
