# Generated by Django 4.0.3 on 2022-03-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_alter_loan_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='date',
            new_name='approved_date',
        ),
    ]
