# Generated by Django 4.0.1 on 2022-02-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_attendance_timestamp_attendance_check_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='working_hours',
            field=models.IntegerField(default=0),
        ),
    ]
