# Generated by Django 4.0.1 on 2022-02-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='working_hours',
            field=models.FloatField(default=0),
        ),
    ]
