# Generated by Django 4.0.1 on 2022-02-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='working_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
