# Generated by Django 4.0.1 on 2022-02-28 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0005_alter_attendance_working_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('working_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('missing_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_leave', models.BooleanField(default=False)),
                ('is_late', models.BooleanField(default=False)),
                ('user', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
