# Generated by Django 4.0.1 on 2022-02-06 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0002_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingstock',
            name='merchandiser',
            field=models.ForeignKey(limit_choices_to={'is_merchandiser': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
