# Generated by Django 4.0.1 on 2022-02-09 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_openingstock_merchandiser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Target',
        ),
    ]
