# Generated by Django 4.0.3 on 2022-03-19 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchandiser', '0001_initial'),
        ('sales', '0003_salereturn_total_amount_salereturn_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingstock',
            name='merchandiser',
            field=models.ForeignKey(limit_choices_to={'is_merchandiser': True}, on_delete=django.db.models.deletion.CASCADE, to='merchandiser.merchandiser'),
        ),
    ]
