# Generated by Django 4.0.3 on 2022-03-19 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchandiser', '0001_initial'),
        ('sales', '0004_alter_openingstock_merchandiser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingstock',
            name='count',
            field=models.PositiveIntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='openingstock',
            name='merchandiser',
            field=models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, to='merchandiser.merchandiser'),
        ),
    ]
