# Generated by Django 4.0.1 on 2022-02-10 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sales_total_amount_saleitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='qty',
        ),
    ]
