# Generated by Django 4.0.3 on 2022-03-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catalogue',
            field=models.URLField(blank=True, max_length=450, null=True),
        ),
    ]
