# Generated by Django 4.0.3 on 2022-03-23 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_catalogue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catalogue',
            new_name='catalogue_url',
        ),
    ]
